name: SonarCloud Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'  # Standard pour J2EE
        distribution: 'temurin'

    - name: Compile Java sources
      run: |
        mkdir -p bin
        find src -name "*.java" > sources.txt
        javac -d bin -cp "WebContent/WEB-INF/lib/*" @sources.txt

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=ibt2
          -Dsonar.projectKey=ibt2_Application_web_de_gestion_des_alertes_noyades
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=src
          -Dsonar.java.binaries=bin
          -Dsonar.java.libraries=WebContent/WEB-INF/lib/*.jar
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.java.source=8
